/************************************
 Decryption algorithm, generated by Cruz 
 Vargas to solve HW1 from Jonathan Katz's 
 Introduction to Classical Cryptography
 ************************************/

#include <stdio.h>

int main(){
    unsigned char ch1, ch2;
    FILE *fpIn, *fpOut;
    int i;
    
//    unsigned char key[KEY_LENGTH] = {0x00, 0x00};
    
    /* of course, I did not use the all-0s key to encrypt */
    
    fpIn = fopen("ctext.txt", "r");
    fpOut = fopen("ptext_decoded.txt", "w");
    i=0;
    
    //Find the key length
    while (fscanf(fpIn, "%c%c", &ch1, &ch2) != EOF) {
        
        if (ch1!='\n' && ch2!='\n') {
            //            fprintf(fpOut, "%02X", ch ^ key[i % KEY_LENGTH]); // ^ is logical XOR
            fprintf(stdout, "%c%c\n", ch1, ch2);
            i++;
        }
    }
    //take every Nth character and calculate frequencies
    
    //Find the key
    

    
    
    fclose(fpIn);  
    fclose(fpOut);  
    return 0;
}
